zowe/jenkins-library

- vars/createPax.groovy
> try to always clean up temp folder

- vars/createPax.groovy
https://github.com/zowe/zowe-install-packaging/issues/140
> issue zowe/zowe-install-packaging#140 lock packaging server

- vars/createPax.groovy
- vars/getArtifactInfoByCLI.groovy
- vars/getArtifactoryBuildInfoByAPI.groovy
- vars/getBuildIdentifier.groovy
- vars/getReleaseIdentifier.groovy
- vars/npmLogin.groovy
- vars/promoteArtifact.groovy
- vars/tagGithubRepository.groovy
- vars/utils.groovy
> fix license for 2019

- vars/npmVersion.groovy
> add npmVersion function

- Jenkinsfile
- src/org/zowe/jenkins_shared_library/scm/GitHub.groovy
- src/test/groovy/org/zowe/jenkins_shared_library/scm/GitHubTest.groovy
- src/test/resources/pipelines/githubTest.groovy
https://github.com/zowe/jenkins-library/issues/29
> Create pull request

- src/org/zowe/jenkins_shared_library/pipelines/generic/GenericPipeline.groovy
> add getPublishTargetPath() method

- src/org/zowe/jenkins_shared_library/pipelines/generic/GenericPipeline.groovy
- src/org/zowe/jenkins_shared_library/pipelines/generic/arguments/GenericSetupArguments.groovy
> issue #41, options to prevent loading default configurations

- src/org/zowe/jenkins_shared_library/docker/Registry.groovy
> give a warning if dockerfile is not found

- src/org/zowe/jenkins_shared_library/Constants.groovy
> change github credential name on lf jenkins

- src/org/zowe/jenkins_shared_library/pipelines/gradle/GradlePipeline.groovy
To address https://github.com/zowe/jenkins-library/issues/9
> Update version for maven publish plugin

- src/org/zowe/jenkins_shared_library/Constants.groovy
> update few lf credentials

- src/org/zowe/jenkins_shared_library/pipelines/generic/GenericPipeline.groovy
Part of https://github.com/zowe/zowe-install-packaging/issues/875
> switch default to new artifactory

- src/org/zowe/jenkins_shared_library/Constants.groovy
Signed-off-by: MarkAckert <mark.ackert@broadcom.com>
> add credential

- build.gradle
> bump version to 1.4.0

- src/org/zowe/jenkins_shared_library/pipelines/generic/GenericPipeline.groovy
> only overwrite baseDirectory when it's not redefined

- src/org/zowe/jenkins_shared_library/npm/Registry.groovy
> pririotize local .npmrc if exists

- src/org/zowe/jenkins_shared_library/pipelines/generic/GenericPipeline.groovy
> make uploadArtifacts public

- src/org/zowe/jenkins_shared_library/pipelines/generic/GenericPipeline.groovy
> allow baseTargetPath to be empty

- src/org/zowe/jenkins_shared_library/pipelines/generic/GenericPipeline.groovy
> redefine protected void bumpVersion()

- src/org/zowe/jenkins_shared_library/pipelines/generic/GenericPipeline.groovy
- src/org/zowe/jenkins_shared_library/pipelines/generic/exceptions/GenericPipelineException.groovy
> keep bumpVersion without argument

- src/org/zowe/jenkins_shared_library/performance/PerformanceTestReport.groovy
- src/org/zowe/jenkins_shared_library/performance/package-info.groovy
Verified with https://wash.zowe.org:8443/view/Performance/job/Zowe%20Performance%20-%20Test/job/users%252Fjack%252Ftest-run-20201122/
> perf test report

- Jenkinsfile
- src/test/resources/pipelines/dockerRegistryTest.groovy
- src/test/resources/pipelines/githubTest.groovy
- src/test/resources/pipelines/jfrogArtifactoryTest.groovy
- src/test/resources/pipelines/npmRegistryTest.groovy
- src/test/resources/pipelines/packageSigningTest.groovy
- src/test/resources/pipelines/paxPackageTest.groovy
> update build label

- src/org/zowe/jenkins_shared_library/artifact/JFrogArtifactory.groovy
> add support of exclusions instead of excludePatterns

- src/org/zowe/jenkins_shared_library/package/Pax.groovy
> fix wrong var name

- src/org/zowe/jenkins_shared_library/pipelines/generic/GenericPipeline.groovy
Signed-off-by: Tom Zhang <tom.yczhang@gmail.com>
> Add initFromFolder

- src/org/zowe/jenkins_shared_library/pipelines/Build.groovy
- src/org/zowe/jenkins_shared_library/pipelines/Constants.groovy
- src/org/zowe/jenkins_shared_library/pipelines/base/Pipeline.groovy
- src/org/zowe/jenkins_shared_library/pipelines/generic/GenericPipeline.groovy
Signed-off-by: Tom Zhang <tom.yczhang@gmail.com>
> Adding get cause and get permission logic

- src/org/zowe/jenkins_shared_library/pipelines/base/Pipeline.groovy
- src/org/zowe/jenkins_shared_library/pipelines/generic/GenericPipeline.groovy
> move authorized user check into stage

- src/org/zowe/jenkins_shared_library/pipelines/Build.groovy
- src/org/zowe/jenkins_shared_library/pipelines/generic/GenericPipeline.groovy
Signed-off-by: Tom Zhang <tom.yczhang@gmail.com>
> adding get surface and root cause and refactoring

- src/org/zowe/jenkins_shared_library/pipelines/base/Pipeline.groovy
- src/org/zowe/jenkins_shared_library/pipelines/base/arguments/EndArguments.groovy
> option to skip email notification
